apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
        - name: flask-app
          image: april48/todo-flask-app:v2
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
          env:
            - name: MONGO_HOST
              value: mongodb
            - name: MONGO_PORT
              value: "27017"
          livenessProbe:
            httpGet:
              path: /
              #path: /badpath
              port: 5000
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              #path: /badpath
              port: 5000
            initialDelaySeconds: 5
            periodSeconds: 10